# Generated by Django 5.2.5 on 2025-08-08 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
